### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by erichardson-lee** [kuraudo-io/nail_care#1]

**Comment by hbjydev** [comment]
@erichardson-lee See the first release for now, I need to write a README soon but haven't got the time rn

**Comment by hbjydev** [comment]
https://github.com/kuraudo-io/nail_care/releases/tag/v1.0.0

**Comment by hbjydev** [comment]
@erichardson-lee Ignore me, just pushed up the README from what I had in the tag. Whatever
